-- =============================================================================
-- OTOMOTO V1 — local / acceptance bootstrap seed
-- =============================================================================
-- Prerequisites (do these first):
--   1. Apply migrations 001 → 007 in order (see README Getting started).
--   2. Create an Auth user in Supabase Dashboard → Authentication → Users
--      (email + password). Copy that user's UUID (auth.users.id).
--
-- What this script does:
--   - Inserts one sample location (Toronto / TOR) if missing
--   - Ensures work_order_sequence starts at 1001 for that location
--
-- What this script does NOT do:
--   - Create Auth users (must be done in the Dashboard or Auth Admin API)
--   - Invent credentials — you supply the real auth_user_id below
--
-- After running the location seed, link your Auth user → app_user → user_location
-- using the commented template at the bottom (replace placeholders).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Sample location + work-order sequence
-- ---------------------------------------------------------------------------
INSERT INTO location (name, code, status)
VALUES ('Toronto', 'TOR', 'active')
ON CONFLICT (code) DO NOTHING;

INSERT INTO work_order_sequence (location_id, next_number)
SELECT location_id, 1001
FROM location
WHERE code = 'TOR'
ON CONFLICT (location_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Link Auth user → app_user (owner) → user_location
-- ---------------------------------------------------------------------------
-- Run AFTER you have created the Auth user and know its UUID.
--
-- Replace:
--   '<AUTH_USER_UUID>'  — auth.users.id from Supabase Auth
--   'you@example.com'   — same email as the Auth user
--   'Ada' / 'Owner'     — display name as you prefer
--
-- Example (uncomment and edit before running):
--
-- INSERT INTO app_user (
--   auth_user_id,
--   first_name,
--   last_name,
--   email,
--   role,
--   status
-- ) VALUES (
--   '<AUTH_USER_UUID>'::uuid,
--   'Ada',
--   'Owner',
--   'you@example.com',
--   'owner',
--   'active'
-- )
-- ON CONFLICT (email) DO UPDATE
--   SET auth_user_id = EXCLUDED.auth_user_id,
--       role = 'owner',
--       status = 'active',
--       updated_at = now();
--
-- INSERT INTO user_location (user_id, location_id)
-- SELECT u.user_id, l.location_id
-- FROM app_user u
-- CROSS JOIN location l
-- WHERE u.email = 'you@example.com'
--   AND l.code = 'TOR'
-- ON CONFLICT (user_id, location_id) DO NOTHING;
--
-- Optional second location (for location-switch / WO-number acceptance):
--
-- INSERT INTO location (name, code, status)
-- VALUES ('Mississauga', 'MIS', 'active')
-- ON CONFLICT (code) DO NOTHING;
--
-- INSERT INTO work_order_sequence (location_id, next_number)
-- SELECT location_id, 1001
-- FROM location
-- WHERE code = 'MIS'
-- ON CONFLICT (location_id) DO NOTHING;
--
-- INSERT INTO user_location (user_id, location_id)
-- SELECT u.user_id, l.location_id
-- FROM app_user u
-- CROSS JOIN location l
-- WHERE u.email = 'you@example.com'
--   AND l.code = 'MIS'
-- ON CONFLICT (user_id, location_id) DO NOTHING;
--
-- Optional non-owner user (for audit-blocked / technician permission tests):
-- Create a second Auth user, then:
--
-- INSERT INTO app_user (
--   auth_user_id, first_name, last_name, email, role, status
-- ) VALUES (
--   '<TECH_AUTH_USER_UUID>'::uuid,
--   'Ty',
--   'Tech',
--   'tech@example.com',
--   'technician',
--   'active'
-- )
-- ON CONFLICT (email) DO UPDATE
--   SET auth_user_id = EXCLUDED.auth_user_id,
--       role = 'technician',
--       status = 'active',
--       updated_at = now();
--
-- INSERT INTO user_location (user_id, location_id)
-- SELECT u.user_id, l.location_id
-- FROM app_user u
-- CROSS JOIN location l
-- WHERE u.email = 'tech@example.com'
--   AND l.code = 'TOR'
-- ON CONFLICT (user_id, location_id) DO NOTHING;
-- =============================================================================
